/**
 * WasmLoader - Utility for loading and managing WebAssembly modules
 */

export class WasmLoader {
    constructor() {
        this.modules = new Map();
    }

    /**
     * Load a WASM module
     * @param {string} name - Module name (e.g., 'stack', 'linkedlist')
     * @param {string} path - Path to the .js file generated by Emscripten
     * @returns {Promise<Object>} - The loaded module
     */
    async load(name, path) {
        if (this.modules.has(name)) {
            return this.modules.get(name);
        }

        try {
            // Dynamically import the Emscripten-generated JavaScript
            const moduleFactory = await import(path);

            // Initialize the module
            const module = await moduleFactory.default();

            this.modules.set(name, module);
            console.log(`✓ Loaded WASM module: ${name}`);
            return module;
        } catch (error) {
            console.error(`Failed to load WASM module '${name}':`, error);
            throw error;
        }
    }

    /**
     * Get a loaded module
     * @param {string} name - Module name
     * @returns {Object|null} - The module or null if not loaded
     */
    get(name) {
        return this.modules.get(name) || null;
    }

    /**
     * Check if a module is loaded
     * @param {string} name - Module name
     * @returns {boolean}
     */
    has(name) {
        return this.modules.has(name);
    }

    /**
     * Load all required WASM modules
     * @returns {Promise<void>}
     */
    async loadAll() {
        const modules = [
            { name: 'stack', path: '../wasm/stack.js' },
            { name: 'linkedlist', path: '../wasm/linkedlist.js' },
            { name: 'hashmap', path: '../wasm/hashmap.js' },
            { name: 'trie', path: '../wasm/trie.js' },
            { name: 'graph', path: '../wasm/graph.js' },
            { name: 'huffman', path: '../wasm/huffman.js' }
        ];

        console.log('Loading WASM modules...');
        await Promise.all(
            modules.map(({ name, path }) => this.load(name, path))
        );
        console.log('✓ All WASM modules loaded successfully');
    }
}

// Singleton instance
export const wasmLoader = new WasmLoader();
